//IMPORTS DE REACT:
//IMPORTS DEPENDENCIAS DE TERCEROS:
//IMPORTS DEPENDENCIAS DE LA APP:
//IMPORTS COMPONENTS DE LA APP:
//IMPORTS Styles DE LA APP:

export const Auth = () => {
  return (
    <h1>Estamos en Auth</h1>
  )
}
